Security app
JavaDev-Latypov-Mikhail/Task-7 pull request #1
Opened 2024-10-10 16:05 UTC by hodkonem

2024-10-11 08:38 UTC, pdasilem requested changes
почему мне кажется, что здесь чатгпт постарался?

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/AdminController.java
> +    private boolean validateUserName(@ModelAttribute("user") User user, BindingResult bindingResult, @RequestParam(value = "roleIds", required = false) List<Long> roleIds, Model model) {
по хорошему, надо бы это вынести в отдельный класс валидатора...

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/LoginController.java
> +public class LoginController {
убирай лишнее.
должны остаться админ и юзер контроллеры

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/models/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
избавиться от игер

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/models/User.java
> +    private List<Long> roleIds;
зачем это поле? не нужно

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +            // Убедитесь, что вы обновляете роли и другие поля, если нужно
?

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +            if (!user.getPassword().equals(existingUser.getPassword())) {
почему это выражение всегда будет тру?

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void save(User user) {
раздели на сейв и апдейт

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void register(User user) {
зачем этот метод, если есть сейв?

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void register(User user, List<Role> roles) {
и еще один

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void update(User user) {
еще и апдейт отдельно

2024-10-11 08:38 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/util/UserValidator.java
> +public class UserValidator implements Validator {
а вот и валидатор нашелся

2024-10-11 12:05 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/AdminController.java
> +    private boolean validateUserName(@ModelAttribute("user") User user, BindingResult bindingResult, @RequestParam(value = "roleIds", required = false) List<Long> roleIds, Model model) {
вынес в отдельный класс

2024-10-11 12:05 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/LoginController.java
> +public class LoginController {
убрал лишнее. Оставил админ и юзер контроллеры.

2024-10-11 12:06 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/models/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
избавился от игер

2024-10-11 12:06 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/models/User.java
> +    private List<Long> roleIds;
Убрал это поле и код с ним связанный

2024-10-11 12:07 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +            // Убедитесь, что вы обновляете роли и другие поля, если нужно
убрал все комментарии

2024-10-11 12:09 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +            if (!user.getPassword().equals(existingUser.getPassword())) {
убрал ненужное сравнение. Чтобы не сравнивать ненужное

2024-10-11 12:09 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void save(User user) {
разделил

2024-10-11 12:10 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void register(User user) {
убрал ненужный метод

2024-10-11 12:10 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void register(User user, List<Role> roles) {
убрал ненужный метод

2024-10-11 12:10 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/services/UserServiceImpl.java
> +    public void update(User user) {
исправил

2024-10-11 12:10 UTC, hodkonem commented on src/main/java/ru/itmentor/spring/boot_security/demo/util/UserValidator.java
> +public class UserValidator implements Validator {
поправил валидатор

2024-10-14 08:59 UTC, pdasilem approved these changes

2024-10-16 14:00 UTC, merged